export const translates: Record<string, Record<string, string>> = {
	'Product Blog': {
		ua: 'Блог продукту',
		bg: 'Продуктов блог',
		hr: 'Blog proizvoda',
		cs: 'Produktový blog',
		da: 'Produktblog',
		nl: 'Productblog',
		en: 'Product Blog',
		et: 'Tooteblogi',
		fi: 'Tuoteblogi',
		fr: 'Blog produit',
		de: 'Produktblog',
		el: 'Ιστολόγιο προϊόντος',
		hu: 'Termékblog',
		ga: 'Blag táirge',
		it: 'Blog del prodotto',
		lv: 'Produkta emuārs',
		lt: 'Produkto tinklaraštis',
		mt: 'Blog tal-prodott',
		pl: 'Blog produktu',
		pt: 'Blog do produto',
		ro: 'Blog de produs',
		sk: 'Produktový blog',
		sl: 'Blog izdelka',
		es: 'Blog del producto',
		sv: 'Produktblogg',
	},
	'Reviews & Guides': {
		ua: 'Огляди та посібники',
		bg: 'Ревюта и ръководства',
		hr: 'Recenzije i vodiči',
		cs: 'Recenze a průvodce',
		da: 'Anmeldelser og guider',
		nl: 'Beoordelingen en gidsen',
		en: 'Reviews & Guides',
		et: 'Arvustused ja juhendid',
		fi: 'Arvostelut ja oppaat',
		fr: 'Avis et guides',
		de: 'Bewertungen und Leitfäden',
		el: 'Αξιολογήσεις και οδηγοί',
		hu: 'Értékelések és útmutatók',
		ga: 'Léirmheasanna agus treoracha',
		it: 'Recensioni e guide',
		lv: 'Atsauksmes un ceļveži',
		lt: 'Apžvalgos ir gidai',
		mt: 'Reċensjonijiet u gwidi',
		pl: 'Recenzje i poradniki',
		pt: 'Avaliações e guias',
		ro: 'Recenzii și ghiduri',
		sk: 'Recenzie a návody',
		sl: 'Ocene in vodniki',
		es: 'Reseñas y guías',
		sv: 'Recensioner och guider',
	},
	'Enter your email': {
		ua: 'Введіть свою електронну пошту',
		bg: 'Въведете своя имейл',
		hr: 'Unesite svoju e-poštu',
		cs: 'Zadejte svůj e-mail',
		da: 'Indtast din e-mail',
		nl: 'Voer je e-mail in',
		en: 'Enter your email',
		et: 'Sisestage oma e-post',
		fi: 'Syötä sähköpostiosoitteesi',
		fr: 'Entrez votre e-mail',
		de: 'Geben Sie Ihre E-Mail ein',
		el: 'Εισαγάγετε το email σας',
		hu: 'Adja meg az e-mail címét',
		ga: 'Cuir isteach do r-phost',
		it: 'Inserisci la tua email',
		lv: 'Ievadiet savu e-pastu',
		lt: 'Įveskite savo el. paštą',
		mt: 'Daħħal l-email tiegħek',
		pl: 'Wpisz swój e-mail',
		pt: 'Insira o seu e-mail',
		ro: 'Introduceți emailul dvs.',
		sk: 'Zadajte svoj e-mail',
		sl: 'Vnesite svoj e-poštni naslov',
		es: 'Introduce tu correo electrónico',
		sv: 'Ange din e-post',
	},
	'Expert reviews, buying guides, and tips for smarter shopping': {
		ua: 'Експертні огляди, посібники з купівлі та поради для розумніших покупок',
		bg: 'Експертни ревюта, ръководства за покупка и съвети за по-умно пазаруване',
		hr: 'Stručne recenzije, vodiči za kupnju i savjeti za pametniju kupovinu',
		cs: 'Odborné recenze, nákupní průvodce a tipy pro chytřejší nakupování',
		da: 'Ekspertanmeldelser, købsguides og tips til smartere shopping',
		nl: 'Expertbeoordelingen, koopgidsen en tips voor slimmer shoppen',
		en: 'Expert reviews, buying guides, and tips for smarter shopping',
		et: 'Ekspertarvustused, ostujuhendid ja nõuanded nutikamaks ostlemiseks',
		fi: 'Asiantuntija-arvosteluja, osto-oppaita ja vinkkejä fiksumpaan ostamiseen',
		fr: "Avis d'experts, guides d'achat et conseils pour des achats plus malins",
		de: 'Expertenbewertungen, Kaufberatungen und Tipps für smarteres Einkaufen',
		el: 'Αξιολογήσεις ειδικών, οδηγοί αγοράς και συμβουλές για πιο έξυπνες αγορές',
		hu: 'Szakértői értékelések, vásárlási útmutatók és tippek az okosabb vásárláshoz',
		ga: 'Léirmheasanna saineolaithe, treoracha ceannaigh, agus leideanna le haghaidh siopadóireachta níos cliste',
		it: "Recensioni di esperti, guide all'acquisto e consigli per acquisti più intelligenti",
		lv: 'Ekspertu atsauksmes, pirkšanas ceļveži un padomi gudrākai iepirkšanās veikšanai',
		lt: 'Ekspertų apžvalgos, pirkimo gidai ir patarimai išmanesniam apsipirkimui',
		mt: "Reċensjonijiet ta' esperti, gwidi tax-xiri, u pariri għal xiri aktar intelliġenti",
		pl: 'Eksperckie recenzje, poradniki zakupowe i wskazówki dotyczące mądrzejszych zakupów',
		pt: 'Avaliações de especialistas, guias de compra e dicas para compras mais inteligentes',
		ro: 'Recenzii de specialitate, ghiduri de cumpărare și sfaturi pentru cumpărături mai inteligente',
		sk: 'Odborné recenzie, nákupné príručky a tipy na múdrejšie nakupovanie',
		sl: 'Strokovne ocene, nakupovalni vodniki in nasveti za pametnejše nakupovanje',
		es: 'Reseñas de expertos, guías de compra y consejos para comprar de forma más inteligente',
		sv: 'Expertrecensioner, köpguider och tips för smartare shopping',
	},
};
